Repository SoLanches/API-SoLanches, pull requests merged in 2021-09, with the labels that each got.

#57 Feature/variaveis ambiente
  .env.example
  README.md
  requirements.txt
  solanches/.env.example
  solanches/__main__.py
  solanches/connect2db.py
  solanches/tests/__init__.py
  solanches/tests/test_controller.py
Labels: backend

#66 Implantacao do pylint e da padronizacao do codigo
  solanches/controller.py
  solanches/models.py
  solanches/rest.py
  solanches/tests/test_rest.py
Labels: test

#75 Atualiza get_produtos e documentação api
  api.md
  solanches/controller.py
  solanches/models.py
Labels: backend

#76 Atualiza assert no edita_produto.
  solanches/controller.py
  solanches/models.py
Labels: backend

#74 Atualiza funcionamento do get_comercios
  api.md
  solanches/controller.py
  solanches/models.py
  solanches/rest.py
Labels: backend

#83 Adiciona rota get_produtos_ids, resolve probelmas em adiciona_destaques e remove_produto
  api.md
  solanches/controller.py
  solanches/models.py
  solanches/rest.py
Labels: backend

#84 Atualização no edita_produto para permitir edição de nome do produto
  api.md
  solanches/controller.py
  solanches/models.py
  solanches/rest.py
Labels: backend

#82 Deletar produto nos destaques do cardapio
  .pylintrc
  api.md
  requirements.txt
  solanches/controller.py
  solanches/models.py
  solanches/rest.py
Labels: backend

#87 Atualiza adiciona_destaques para receber produto_id
  api.md
  solanches/controller.py
  solanches/models.py
  solanches/rest.py
Labels: backend

#88 Feature/cadastro categorias cardapio
  api.md
  solanches/controller.py
  solanches/models.py
  solanches/rest.py
Labels: backend

#85 Adiciona login com JWT
  requirements.txt
  solanches/authenticate.py
  solanches/connect2db.py
  solanches/controller.py
  solanches/models.py
  solanches/rest.py
Labels: backend

#86 tratamento de excecao
  solanches/authenticate.py
  solanches/controller.py
  solanches/errors.py
  solanches/models.py
  solanches/rest.py
  solanches/tests/test_controller.py
  solanches/tests/test_rest.py
Labels: backend

#110 Atualiza Documentação API.
  api.md
Labels: documentation

#107 Test/get produto
  solanches/controller.py
  solanches/tests/data_test.py
  solanches/tests/test_controller.py
  solanches/tests/test_rest.py
Labels: test

#109 Test/delete produto
  solanches/rest.py
  solanches/tests/data_test.py
  solanches/tests/test_controller.py
  solanches/tests/test_rest.py
Labels: test

#108 Test/post categoria
  solanches/tests/data_test.py
  solanches/tests/test_controller.py
  solanches/tests/test_rest.py
Labels: test

#58 Ts-S04-T01: Testar POST /comercio
  solanches/controller.py
  solanches/tests/_init_.py
  solanches/tests/data_test.py
  solanches/tests/test_controller.py
  solanches/tests/test_rest.py
Labels: test

#113 Test/post destaque produto
  solanches/tests/test_controller.py
  solanches/tests/test_rest.py
Labels: test

#117 Teste/delete categoria
  solanches/tests/data_test.py
  solanches/tests/test_controller.py
  solanches/tests/test_rest.py
Labels: test
